# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  lukitoharjo.com:
    site_hosts:
      - canonical: lukitoharjo.test
        redirects:
          - www.lukitoharjo.test
    local_path: ../lukitoharjo.com # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@lukitoharjo.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
  adminmu.id:
    site_hosts:
      - canonical: adminmu.test
        redirects:
          - www.adminmu.test
    local_path: ../adminmu.id # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@adminmu.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
      
